-- =========================================================
-- Finance Module Schema
-- Purpose:
-- - Daftra integration registry without storing raw keys.
-- - Incoming/outgoing financial transactions.
-- - Stored financial statements generated by the finance agent.
-- =========================================================

create extension if not exists pgcrypto;

create table if not exists public.finance_daftra_integrations (
  id uuid primary key default gen_random_uuid(),
  integration_key text not null unique default 'daftra.primary',
  display_name text not null default 'Daftra Primary',
  base_url text,
  tenant_name text,
  account_identifier text,
  auth_type text not null default 'server_secret' check (auth_type in ('server_secret', 'bearer_token', 'api_key', 'oauth2', 'none')),
  secret_refs jsonb not null default '{"api_key":"DAFTRA_API_KEY"}'::jsonb,
  endpoint_map jsonb not null default '{"invoices":"/api2/invoices","expenses":"/api2/expenses","payments":"/api2/payments","clients":"/api2/clients"}'::jsonb,
  sync_config jsonb not null default '{"direction":"pull","auto_sync":false}'::jsonb,
  last_sync_at timestamptz,
  last_health_status text not null default 'unknown' check (last_health_status in ('unknown', 'ok', 'warning', 'failed', 'disabled')),
  last_health_message text,
  is_enabled boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint finance_daftra_base_url_https_chk check (base_url is null or base_url like 'https://%')
);

create table if not exists public.finance_transactions (
  id uuid primary key default gen_random_uuid(),
  source text not null default 'manual' check (source in ('manual', 'daftra', 'import', 'agent')),
  direction text not null check (direction in ('incoming', 'outgoing')),
  document_type text not null default 'entry' check (document_type in ('invoice', 'receipt', 'expense', 'bill', 'payment', 'journal', 'entry')),
  document_no text,
  party_name text,
  party_type text check (party_type in ('customer', 'supplier', 'employee', 'owner', 'other')),
  tx_date date not null default current_date,
  due_date date,
  currency text not null default 'EGP',
  subtotal numeric(14,2) not null default 0,
  tax numeric(14,2) not null default 0,
  discount numeric(14,2) not null default 0,
  total numeric(14,2) generated always as (subtotal + tax - discount) stored,
  paid_amount numeric(14,2) not null default 0,
  status text not null default 'draft' check (status in ('draft', 'issued', 'paid', 'partial', 'overdue', 'cancelled')),
  account_code text,
  category text,
  cost_center text,
  project_ref text,
  description text,
  daftra_id text,
  daftra_payload jsonb not null default '{}'::jsonb,
  attachments jsonb not null default '[]'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint finance_transactions_amounts_non_negative_chk check (subtotal >= 0 and tax >= 0 and discount >= 0 and paid_amount >= 0),
  constraint finance_transactions_daftra_unique unique (source, daftra_id)
);

create table if not exists public.finance_statements (
  id uuid primary key default gen_random_uuid(),
  statement_key text not null unique,
  statement_type text not null check (statement_type in ('income_statement', 'cash_flow', 'balance_sheet', 'trial_balance', 'executive_report')),
  period_start date,
  period_end date,
  currency text not null default 'EGP',
  source text not null default 'agent' check (source in ('manual', 'daftra', 'agent', 'import')),
  data jsonb not null default '{}'::jsonb,
  narrative_report text,
  agent_model_id text,
  agent_deployment_name text,
  log_id uuid,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_finance_transactions_direction on public.finance_transactions(direction);
create index if not exists idx_finance_transactions_date on public.finance_transactions(tx_date desc);
create index if not exists idx_finance_transactions_status on public.finance_transactions(status);
create index if not exists idx_finance_transactions_source on public.finance_transactions(source);
create index if not exists idx_finance_transactions_daftra_id on public.finance_transactions(daftra_id);
create index if not exists idx_finance_transactions_payload on public.finance_transactions using gin(daftra_payload);
create index if not exists idx_finance_statements_type on public.finance_statements(statement_type);
create index if not exists idx_finance_statements_period on public.finance_statements(period_start, period_end);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_finance_daftra_integrations_updated_at on public.finance_daftra_integrations;
create trigger trg_finance_daftra_integrations_updated_at
before update on public.finance_daftra_integrations
for each row execute function public.set_updated_at();

drop trigger if exists trg_finance_transactions_updated_at on public.finance_transactions;
create trigger trg_finance_transactions_updated_at
before update on public.finance_transactions
for each row execute function public.set_updated_at();

drop trigger if exists trg_finance_statements_updated_at on public.finance_statements;
create trigger trg_finance_statements_updated_at
before update on public.finance_statements
for each row execute function public.set_updated_at();

alter table public.finance_daftra_integrations enable row level security;
alter table public.finance_transactions enable row level security;
alter table public.finance_statements enable row level security;

drop policy if exists "finance_daftra_admin_all" on public.finance_daftra_integrations;
drop policy if exists "finance_transactions_admin_all" on public.finance_transactions;
drop policy if exists "finance_statements_admin_all" on public.finance_statements;

create policy "finance_daftra_admin_all"
on public.finance_daftra_integrations
for all
to authenticated
using (public.has_role(auth.uid(), 'admin'))
with check (public.has_role(auth.uid(), 'admin'));

create policy "finance_transactions_admin_all"
on public.finance_transactions
for all
to authenticated
using (public.has_role(auth.uid(), 'admin'))
with check (public.has_role(auth.uid(), 'admin'));

create policy "finance_statements_admin_all"
on public.finance_statements
for all
to authenticated
using (public.has_role(auth.uid(), 'admin'))
with check (public.has_role(auth.uid(), 'admin'));

insert into public.finance_daftra_integrations (
  integration_key,
  display_name,
  base_url,
  tenant_name,
  auth_type,
  secret_refs,
  endpoint_map,
  sync_config,
  is_enabled
)
values (
  'daftra.primary',
  'Daftra Primary',
  null,
  null,
  'server_secret',
  '{"api_key":"DAFTRA_API_KEY"}'::jsonb,
  '{"invoices":"/api2/invoices","expenses":"/api2/expenses","payments":"/api2/payments","clients":"/api2/clients"}'::jsonb,
  '{"direction":"pull","auto_sync":false,"note":"Set exact Daftra endpoints after confirming account API paths."}'::jsonb,
  true
)
on conflict (integration_key) do update set
  display_name = excluded.display_name,
  secret_refs = finance_daftra_integrations.secret_refs,
  endpoint_map = coalesce(finance_daftra_integrations.endpoint_map, excluded.endpoint_map),
  sync_config = coalesce(finance_daftra_integrations.sync_config, excluded.sync_config),
  updated_at = now();
